# Generated by Django 5.0.2 on 2025-03-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
