# Generated by Django 5.0.2 on 2025-03-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_description_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='Check Price on Amazon', max_length=50),
        ),
    ]
